"""
插件生成器工具 - 用于快速生成插件模板
"""

import os
import sys
import argparse
from datetime import datetime


def create_plugin_template(plugin_name: str, description: str = None):
    """创建插件模板"""
    if not description:
        description = f"{plugin_name} 插件"

    plugin_content = f'''# -*- coding: utf-8 -*-

# @Author  : Auto-generated by Plugin Generator
# @Time    : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

import requests
import time
from typing import Dict, Any, List
from subscribe.logger import logger


def main(params: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    {plugin_name} 插件主函数

    Args:
        params: 插件参数字典

    Returns:
        插件执行结果列表
    """
    logger.info(f"[{plugin_name}] 开始执行插件，参数: {{params}}")

    try:
        # 在这里实现插件的主要逻辑
        # 示例：发起HTTP请求
        base_url = params.get("base_url", "https://example.com")
        timeout = params.get("timeout", 30)

        # 示例请求
        response = requests.get(base_url, timeout=timeout)
        response.raise_for_status()

        # 处理响应数据
        data = response.json() if response.headers.get('content-type', '').startswith('application/json') else response.text

        # 构造返回结果
 result = {{
            "status": "success",
            "message": "{description} 执行成功",
            "timestamp": int(time.time()),
            "data": data,
            "params": params
        }}

        logger.info(f"[{plugin_name}] 插件执行完成，结果: {{result}}")
        return [result]

    except requests.exceptions.RequestException as e:
 error_result = {{
            "status": "error",
            "message": f"请求失败: {{str(e)}}",
            "timestamp": int(time.time()),
            "params": params
        }}
        logger.error(f"[{plugin_name}] 插件执行失败: {{error_result}}")
        return [error_result]
    except Exception as e:
        error_result = {{
            "status": "error",
            "message": f"插件执行异常: {{str(e)}}",
            "timestamp": int(time.time()),
            "params": params
        }}
        logger.error(f"[{plugin_name}] 插件执行异常: {{error_result}}")
        return [error_result]


if __name__ == "__main__":
    # 测试插件功能
    test_params = {{
        "base_url": "https://httpbin.org/get",
        "timeout": 10
    }}
    result = main(test_params)
    print(f"插件测试结果: {{result}}")
'''

    # 确保scripts目录存在
    scripts_dir = os.path.join(
        os.path.dirname(
            os.path.dirname(__file__)),
        'subscribe',
        'scripts')
    if not os.path.exists(scripts_dir):
        os.makedirs(scripts_dir)

    # 创建插件文件
    plugin_path = os.path.join(scripts_dir, f"{plugin_name}.py")
    with open(plugin_path, 'w', encoding='utf-8') as f:
        f.write(plugin_content)

    print(f"插件模板已创建: {plugin_path}")
    return plugin_path


def create_plugin_config(
        plugin_name: str,
        description: str = None,
        enabled: bool = False):
    """创建插件配置"""
    if not description:
        description = f"{plugin_name} 插件"

    config = {
        "module_path": f"subscribe.scripts.{plugin_name}",
        "function_name": "main",
        "enabled": enabled,
        "cron_schedule": "",
        "parameters": {
            "base_url": "https://example.com",
            "timeout": 30
        },
        "timeout": 300,
        "max_retries": 3
    }

    return {plugin_name: config}


def main():
    parser = argparse.ArgumentParser(description='插件生成器工具')
    parser.add_argument('name', help='插件名称')
    parser.add_argument('-d', '--description', help='插件描述')
    parser.add_argument('-e', '--enable', action='store_true', help='是否启用插件')
    parser.add_argument(
        '--add-to-config',
        action='store_true',
        help='是否添加到配置文件')

    args = parser.parse_args()

    # 创建插件模板
    plugin_path = create_plugin_template(
        args.name, args.description or f"{args.name} 插件")

    if args.add_to_config:
        # 添加到配置文件
        config_path = os.path.join(
            os.path.dirname(
                os.path.dirname(__file__)),
            'config',
            'plugin_config.json')

        import json
        import os
        from collections import OrderedDict

        # 读取现有配置或创建新配置
        if os.path.exists(config_path):
            with open(config_path, 'r', encoding='utf-8') as f:
                config = json.load(f)
        else:
            config = {"plugins": {}}

        # 添加新插件配置
        plugin_config = create_plugin_config(
            args.name, args.description, args.enable)
        config["plugins"].update(plugin_config)

        # 写入配置文件
        os.makedirs(os.path.dirname(config_path), exist_ok=True)
        with open(config_path, 'w', encoding='utf-8') as f:
            json.dump(
                config,
                f,
                ensure_ascii=False,
                indent=2,
                separators=(
                    ',',
                    ': '))

        print(f"插件配置已添加到: {config_path}")

    print(f"插件 '{args.name}' 生成完成！")
    print(f"路径: {plugin_path}")
    print("请根据需要修改插件代码和参数配置。")


if __name__ == "__main__":
    main()
